### ISSUE TITLE
Step 7: I'm using the Kraken2 DB from galaxylab:/home/raphenar/sars-cov-2/round1/human/Iran1-LA/kraken/db. Is this okay or should we use something different?

### ISSUE THREAD

**Issue by raphenya** [jaleezyy/covid-19-sequencing#8]

**Comment by jaleezyy** [comment]
Have we run `kraken2-build --clean --db db`? Would that not drop the file size of the db considerably?

**Comment by jaleezyy** [comment]
Reduction of kraken2 db after the above is 371M. Seems worth running for the final kraken2 db @kmsmith137 @raphenya.

**Comment by fmaguire** [comment]
That would make it small enough to allow us to distribute it easily instead of making people build it locally.

On that topic: we may have to figure out the segfault issue with kraken 2.0.8.  Kraken 2.0.7 uses the old (now broken) FTP paths to get taxonomy data from NCBI.  This means with the version of kraken in the conda env we can't automated database setup currently.

**Comment by fmaguire** [comment]
@jaleezyy have you run an output comparison for this smaller DB vs the original full DB?

**Comment by jaleezyy** [comment]
@fmaguire Results are identical. The cleanup mainly removes the now unneeded NCBI taxonomy files (which make up the bulk of the DB).

**Comment by fmaguire** [comment]
Great your commit: 3f60b12d2 resolves this then.
